//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1rcmxAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliento
    {
        public int id_cli { get; set; }
        public string RFC { get; set; }
        public string NomCli { get; set; }
        public string CveRegimen { get; set; }
        public string CalCli { get; set; }
        public string NinCli { get; set; }
        public string NexCli { get; set; }
        public string ColCli { get; set; }
        public string EstCli { get; set; }
        public string CodCli { get; set; }
        public string CveUsoCFDICli { get; set; }
        public string FechaRegistro { get; set; }
        public Nullable<int> Saldo { get; set; }
        public string Correo { get; set; }
    }
}
