//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1rcmxAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientoUsuario
    {
        public int id_usr { get; set; }
        public string usrRFC { get; set; }
        public string usrPSW { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
    }
}
